name: CleanArchitecture - PR

env:
  DOTNET_VERSION: 9.0.x

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet restore
        run: dotnet restore CleanArchitecture.sln
        
      - name: dotnet test
        run: dotnet test CleanArchitecture.sln
        
      # - name: dotnet publish
      #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/CleanArchitecture
      